import { readdirSync, writeFileSync } from 'node:fs';
import { basename, extname, join, resolve } from 'node:path';

const commandsDir = resolve('src/commands');
const outputFile = resolve(commandsDir, 'commands.generated.ts');

interface CommandFile {
  importPath: string;
  exportName: string;
}

/**
 * Recursively retrieves all command file information from a specified directory.
 *
 * @param {string} dir The directory path to search for command files.
 * @param {string} [base='.'] The base path used to generate relative import paths.
 * @return {CommandFile[]} An array of command file objects, each containing the `importPath` and `exportName`.
 */
function getCommandFiles(dir: string, base: string = '.'): CommandFile[] {
  const entries = readdirSync(dir, { withFileTypes: true });

  return entries.flatMap((entry) => {
    const fullPath = join(dir, entry.name);

    // avoid including the generated file
    if (entry.name === 'commands.generated.ts') return [];

    if (entry.isDirectory()) {
      return getCommandFiles(fullPath, join(base, entry.name));
    }

    if (/\.(ts|js)$/.test(entry.name)) {
      const noExt = basename(entry.name, extname(entry.name));
      const exportName = normalizeExportName(noExt);

      // generate import relative to the generated file
      const relPath = './' + join(base, noExt).replace(/\\/g, '/');

      return {
        importPath: relPath,
        exportName,
      };
    }

    return [];
  });
}

function normalizeExportName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]/g, '_');
}

function generateFile(files: CommandFile[]): string {
  const header = `// AUTO-GENERATED FILE. DO NOT EDIT.
// This file is generated by scripts/generate-commands.ts
// Run "bun generate:commands" to regenerate.

import type BaseCommand from '../interfaces/BaseCommand';
`;

  const imports = files.map(({ importPath, exportName }) => `import ${exportName} from '${importPath}';`).join('\n');

  const array = `
const commands: BaseCommand[] = [
${files.map(({ exportName }) => `  new ${exportName}(),`).join('\n')}
];

export default commands;
`;

  return [header, imports, array].join('\n');
}

const files = getCommandFiles(commandsDir);
const content = generateFile(files);

writeFileSync(outputFile, content);

console.log(`✅ Generated ${files.length} commands into ${outputFile}`);
